name: Auto Approve

on:
  pull_request:
    types:
      - labeled

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    steps:
      - name: Auto Approve
        if: github.event.label.name == 'auto approve'
        uses: actions/github-script@v5
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.rest.pulls.createReview({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
              event: 'APPROVE'
            })
